[package]
name = "envelope-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
clap.workspace = true
envelope-core = { path = "../../crates/envelope-core" }
envelope-server-core = { path = "../../crates/envelope-server-core" }
etcd-client = { version = "=0.20.0", features = ["tls-ring"] }
fs2.workspace = true
sha2.workspace = true
hex.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
